[package]
name = "http-sink"
group = "infinyon"
version = "0.2.2"
apiVersion = "0.1.0"
fluvio = "0.10.9"
description = "HTTP sink connector reads records from data streaming and generates an HTTP request"
license = "Apache-2.0"
visibility = "public"

[direction]
dest = true 

[deployment]
binary = "http-sink"
