[package]
name = "http"
group = "john"
version = "0.1.0"
apiVersion = "0.1.0"
fluvio = "0.10.0"
description = ""
license = "Apache-2.0"
visibility = "public"

[direction]
dest = true 

[deployment]
binary = "http-sink"
