name: Publish Hub Dev

permissions: read-all

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to checkout"
        required: true
        type: string
        default: "main"

jobs:
  publish:
    uses: infinyon/fluvio/.github/workflows/connector-publish.yml@morenol-patch-1
    with:
      package-name: http-sink
      branch: ${{ github.event.inputs.branch }}
      cloud-url: ${{ vars.DEV_CLOUD_URL }}
      fail-fast: false  
    secrets:
      CLOUD_USER_EMAIL: ${{ secrets.DEV_HUB_USER_EMAIL }}
      CLOUD_USER_PASSWORD: ${{ secrets.DEV_HUB_USER_PASSWORD }}
